nginx:
  container_name: registry-proxy
  image: arturskovalenko/registry-nginx-ldap-proxy:0.1
  # build: .
  ports:
    - 5043:443
  net: ${CUSTOM_NETWORK_NAME}
  # volumes:
    # - ./nginx/conf.d:/etc/nginx/conf.d:ro
    # - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  environment:
    # Specify the IP address or domain name for the SSL certificates
    # It left empty, it will be automatically obtained using myip.opendns.com
    - "ROOT_COMMON_NAME="
    - "LDAP_SERVER=ldap:389"
    - "LDAP_USERNAME=cn=admin,${LDAP_FULL_DOMAIN}"
    - "LDAP_PASSWORD=${LDAP_PWD}"
    - "LDAP_USER_BASE_DN=ou=people,${LDAP_FULL_DOMAIN}"
    - "LDAP_GROUP_ATTRIBUTE=member"
    - "LDAP_USER_ID_ATTRIBUTE=cn"
    - "LDAP_USER_OBJECT_CLASS=inetOrgPerson"

registry:
  container_name: registry
  image: registry:2
  # Alternative is to use "secure" adop-docker-registry image with self-signed certificates
  # image: adop-docker-registry:0.1
  net: ${CUSTOM_NETWORK_NAME}
  ports:
    - 127.0.0.1:5500:5000
  environment:
    REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
  volumes:
    - /data:/data